const verbs = [
  "Act",
  "Answer",
  "Approve",
  "Arrange",
  "Break",
  "Build",
  "Buy",
  "Coach",
  "Color",
  "Cough",
  "Create",
  "Complete",
  "Cry",
  "Dance",
  "Describe",
  "Draw",
  "Drink",
  "Eat",
  "Edit",
  "Enter",
  "Exit",
  "Imitate",
  "Invent",
  "Jump",
  "Laugh",
  "Lie",
  "Listen",
  "Paint",
  "Plan",
  "Play",
  "Read",
  "Replace",
  "Run",
  "Scream",
  "See",
  "Shop",
  "Shout",
  "Sing",
  "Skip",
  "Sleep",
  "Sneeze",
  "Solve",
  "Study",
  "Teach",
  "Touch",
  "Turn",
  "Walk",
  "Win",
  "Write",
  "Whistle",
  "Yank",
  "Zip",
];
function verbDisplay() {
  document.getElementById("verb-dis").innerHTML =
    verbs[Math.floor(Math.random() * verbs.length)];
  const randomColor = Math.floor(Math.random() * 16777215).toString(16);
  document.body.style.backgroundColor = "#" + randomColor;
  color.innerHTML = "#" + randomColor;
}
