const verbs = [
  "bring",
  "build",
  "burn",
  "beat",
  "bite",
  "become",
  "bear",
  "blow",
  "catch",
  "come",
  "choose",
  "do",
  "dig",
  "dug",
  "drink",
  "drive",
  "Eat",
  "fight",
  "fly",
  "forget",
  "feel",
  "feed",
  "give",
  "go",
  "grow",
  "get",
  "hold",
  "hide",
  "have",
  "keep",
  "know",
  "lay",
  "learn",
  "lose",
  "lend",
  "meet",
  "mean",
  "make",
  "pay",
  "ring",
  "run",
  "rise",
  "ride",
  "say",
  "send",
  "sell",
  "spend",
  "sleep",
  "sit",
  "sing",
  "sink",
  "speak",
  "stand",
  "stick",
  "strike",
  "sweep",
  "swim",
  "see",
  "shake",
  "take",
  "throw",
  "tear",
  "teach",
  "tell",
  "think",
  "wear",
  "win",
  "write",
  "weep",
];
const unchanging_verbs = [
  "bet",
  "cast",
  "cut",
  "hit",
  "hurt",
  "put",
  "set",
  "shut",
  "spread",
  "telecast",
  "broadcast",
  "burst",
  "cost",
  "let",
];
const regular_verbs = [
  "borrow",
  "advance",
  "affect",
  "admire",
  "act",
  "accommodate",
  "abscond",
  "attack",
  "argue",
  "arrive",
  "appoint",
  "aim",
  "arrange",
  "advise",
  "appear",
  "admit",
  "accept",
  "agree",
  "announce",
  "ask",
  "Believe",
  "blame",
  "bother",
  "call",
  "cancel",
  "consider",
  "change",
  "cheat",
  "criticise",
  "cry",
  "capture",
  "carry",
  "collect",
  "convert",
  "continue",
  "convey",
  "clash",
  "calculate",
  "clarify",
  "challenge",
  "communicate",
  "Close",
  "count",
  "chase",
  "dispatch",
  "depend",
  "dismiss",
  "depart",
  "delay",
  "demand",
  "discuss",
  "desire",
  "dash",
  "deliver",
  "decrease",
  "divide",
  "drown",
  "expect",
  "enjoy",
  "enquire",
  "Instruct",
  "invent",
  "increase",
  "insist",
  "interfere",
  "interrupt",
  "introduce",
  "interest",
  "impress",
  "inform",
  "hesitate",
  "happen",
  "help",
  "guess",
  "guide",
  "gather",
  "follow",
  "fine",
  "frighten",
  "fear",
  "frame",
  "float",
  "fail",
  "form",
  "Present",
  "play",
  "purchase",
  "perform",
  "prove",
  "pass",
  "owe",
  "mourn",
  "neglect",
  "manufacture",
  "murmur",
  "move",
  "lecture",
  "look",
  "lift",
  "listen",
  "love",
  "like",
  "kidnap",
  "kill",
  "join",
  "invite",
  "jump",
  "Release",
  "reject",
  "require",
  "remind",
  "release",
  "reflect",
  "recall",
  "ridicule",
  "report",
  "remark",
  "remain",
  "return",
  "refuse",
  "quarrel",
  "possess",
  "practise",
  "place",
  "punish",
  "prevent",
  "permit",
  "push",
  "pull",
  "Trust",
  "treat",
  "temp",
  "try",
  "travel",
  "transfer",
  "turn",
  "sympathise",
  "step",
  "surprise",
  "scold",
  "select",
  "stop",
  "search",
  "seize",
  "suffer",
  "suspect",
  "support",
  "suggest",
  "spoil",
  "store",
  "remind",
  "require",
  "reject",
  "Train",
  "threaten",
  "use",
  "vote",
  "vex",
  "verify",
  "want",
  "walk",
  "waste",
  "warn",
  "worry",
  "yawn",
  "zip",
];
function verbDisplay() {
  document.getElementById("regular-dis").innerHTML = "";
  document.getElementById("unchanging-dis").innerHTML = "";
  document.getElementById("verb-dis").innerHTML =
    verbs[Math.floor(Math.random() * verbs.length)];
  const randomColor = Math.floor(Math.random() * 16777215).toString(16);
  document.body.style.backgroundColor = "#" + randomColor;
  color.innerHTML = "#" + randomColor;
}

function unchangingDisplay() {
  document.getElementById("regular-dis").innerHTML = "";
  document.getElementById("verb-dis").innerHTML = "";
  document.getElementById("unchanging-dis").innerHTML =
    unchanging_verbs[Math.floor(Math.random() * unchanging_verbs.length)];
  const randomColor = Math.floor(Math.random() * 16777215).toString(16);
  document.body.style.backgroundColor = "#" + randomColor;
  color.innerHTML = "#" + randomColor;
}

function regularDisplay() {
  document.getElementById("unchanging-dis").innerHTML = "";
  document.getElementById("verb-dis").innerHTML = "";
  document.getElementById("regular-dis").innerHTML =
    regular_verbs[Math.floor(Math.random() * regular_verbs.length)];
  const randomColor = Math.floor(Math.random() * 16777215).toString(16);
  document.body.style.backgroundColor = "#" + randomColor;
  color.innerHTML = "#" + randomColor;
}
function exit_reset() {
  window.location.reload();
}
